/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    Arrow: typeof import('./src/components/Arrow.vue')['default']
    Career: typeof import('./src/components/Career.vue')['default']
    CareerList: typeof import('./src/components/CareerList.vue')['default']
    Contact: typeof import('./src/components/Contact.vue')['default']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    Elev: typeof import('./src/components/Elev.vue')['default']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    GalleryList: typeof import('./src/components/GalleryList.vue')['default']
    GalleryMain: typeof import('./src/components/GalleryMain.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    News: typeof import('./src/components/News.vue')['default']
    Personnel: typeof import('./src/components/Personnel.vue')['default']
    Reviews: typeof import('./src/components/Reviews.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Services: typeof import('./src/components/Services.vue')['default']
    Subscribe: typeof import('./src/components/Subscribe.vue')['default']
    Testimonials: typeof import('./src/components/Testimonials.vue')['default']
    Video: typeof import('./src/components/Video.vue')['default']
  }
}
